name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '1.1.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm test
      
      # Check if package name is scoped (starts with @)
      - name: Check if package name is scoped
        id: package-check
        run: |
          IS_SCOPED=$(node -e "const pkg = require('./package.json'); console.log(pkg.name.startsWith('@') ? 'true' : 'false');")
          echo "IS_SCOPED=$IS_SCOPED" >> $GITHUB_ENV
          echo "Package name from package.json: $(node -e "console.log(require('./package.json').name)")"
      
      # Publish package based on whether it's scoped or not
      - name: Publish package
        run: |
          if [ "$IS_SCOPED" = "true" ]; then
            echo "Publishing scoped package with --access public"
            npm publish --access public
          else
            echo "Publishing regular package"
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}